spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev
    application:
         name: vs-config-dev
---
spring:
    profiles: test
    application:
         name: vs-config-test