spring: 
  profiles:
    active:
    - dev
---
spring: 
  profiles: dev
    application: 
      name: vs-cloud-config-dev
---
spring: 
  profiles: test
    application: 
      name: vs-cloud-config-test
#    请保存为UTF-8格式