spring:
    profiles:
        active:
        - dev
---
server:
    port: 8201
spring:
    profiles: dev
    application:
        name: vs-server-config-client
eureka:
    client:
        service-url:
            defaultZone: http://eureka-dev.com:7002/eureka/ 
---
server:
    port: 8202
spring:
    profiles: test
    application:
        name: vs-server-config-client
eureka:
    client:
        service-url:
            defaultZone: http://eureka-test.com:7002/eureka/ 